---
title: "A Guide for Instructors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SppDistMonProj}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Te SppDistMonProj package was developed to be used as an aid for teaching data management and workflow concepts using R. This vignette provides an introduction of the SppDistMonProj R package for a course instructor. It provides step-by-step instructions on how to use the package to teach applied data management concepts.

## The Example Survey

This package uses a mock survey to show how R can be used to develop a data workflow that includes many steps of a data life cycle including importing, processing, analyzing and reporting on data. The objective of the mock survey is to estimate the occupancy of a species within a sampling frame. Occupancy is a function of environmental covariates. To do this, package functions simulate the spatial distribution of environmental covariates in the sampling frame. Based on the distribution of these covariates, a package function simulates the distribution of the target species of interest.   

## Overview

The first step is to introduce a basic approach for developing scripts in R to import, process, analyze and report on data. 

Here's where instructions on how to use the package will go.

## Questions and Feedback

Contact [Jared Laufenberg](mailto: jared_laufenberg@fws.gov) or 
[McCrea Cobb](mailto: mccrea_cobb@fws.gov). 
